//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountEntities : DbContext
    {
        public AccountEntities()
            : base("name=AccountEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SArea> SAreas { get; set; }
        public DbSet<SBank> SBanks { get; set; }
        public DbSet<SBankBranch> SBankBranches { get; set; }
        public DbSet<SCheckList_Config> SCheckList_Config { get; set; }
        public DbSet<SColor> SColors { get; set; }
        public DbSet<SCompany> SCompanies { get; set; }
        public DbSet<SCompanyModule> SCompanyModules { get; set; }
        public DbSet<SConfig> SConfigs { get; set; }
        public DbSet<SCountry> SCountries { get; set; }
        public DbSet<SDistrict> SDistricts { get; set; }
        public DbSet<SErrorLog> SErrorLogs { get; set; }
        public DbSet<SFeature> SFeatures { get; set; }
        public DbSet<SHospital> SHospitals { get; set; }
        public DbSet<SLevelCompany> SLevelCompanies { get; set; }
        public DbSet<SLevelEducation> SLevelEducations { get; set; }
        public DbSet<SLevelForeignLanguage> SLevelForeignLanguages { get; set; }
        public DbSet<SLevelInformatic> SLevelInformatics { get; set; }
        public DbSet<SLevelProfession> SLevelProfessions { get; set; }
        public DbSet<SMaritalStatu> SMaritalStatus { get; set; }
        public DbSet<SMenu> SMenus { get; set; }
        public DbSet<SMenuCategory> SMenuCategories { get; set; }
        public DbSet<SModule> SModules { get; set; }
        public DbSet<SMoneyType> SMoneyTypes { get; set; }
        public DbSet<SPermission> SPermissions { get; set; }
        public DbSet<SProfessionType> SProfessionTypes { get; set; }
        public DbSet<SProvince> SProvinces { get; set; }
        public DbSet<SRace> SRaces { get; set; }
        public DbSet<SReligion> SReligions { get; set; }
        public DbSet<SRoLe> SRoLes { get; set; }
        public DbSet<SRolePermission> SRolePermissions { get; set; }
        public DbSet<SStatu> SStatus { get; set; }
        public DbSet<SUnit> SUnits { get; set; }
        public DbSet<SUser> SUsers { get; set; }
        public DbSet<SUserRole> SUserRoles { get; set; }
    }
}
