//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_BreakSchedule
    {
        public HR_BreakSchedule()
        {
            this.HR_DailyWorkSchedule = new HashSet<HR_DailyWorkSchedule>();
            this.HR_OverTime = new HashSet<HR_OverTime>();
        }
    
        public int BreakScheduleId { get; set; }
        public string Name { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public Nullable<double> Paid { get; set; }
        public Nullable<double> UnPaid { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<HR_DailyWorkSchedule> HR_DailyWorkSchedule { get; set; }
        public virtual ICollection<HR_OverTime> HR_OverTime { get; set; }
    }
}
