//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ContractDetail
    {
        public HR_ContractDetail()
        {
            this.HR_ContractAllowances = new HashSet<HR_ContractAllowances>();
            this.HR_ContractDetail1 = new HashSet<HR_ContractDetail>();
            this.HR_CycleWageHistory = new HashSet<HR_CycleWageHistory>();
            this.HR_TimeKeepingSumary = new HashSet<HR_TimeKeepingSumary>();
        }
    
        public int ContractDetailID { get; set; }
        public int ContractId { get; set; }
        public string No { get; set; }
        public Nullable<int> ParentContractDetailId { get; set; }
        public int ContractTypeID { get; set; }
        public int ContractTimeID { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public int MoneyTypeID { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> SignUser { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime ExpingDate { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal SocialIncuranceSalary { get; set; }
        public decimal TotalAllowamces { get; set; }
        public decimal TotalIncome { get; set; }
        public Nullable<int> PayRollWageID { get; set; }
        public int FormPaymentID { get; set; }
        public Nullable<int> CycleWage { get; set; }
        public string AttachFile { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BankBranchId { get; set; }
        public string AccountNo { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ContractTemplate1 { get; set; }
        public Nullable<int> ContractTemplate2 { get; set; }
    
        public virtual HR_Contract HR_Contract { get; set; }
        public virtual ICollection<HR_ContractAllowances> HR_ContractAllowances { get; set; }
        public virtual ICollection<HR_ContractDetail> HR_ContractDetail1 { get; set; }
        public virtual HR_ContractDetail HR_ContractDetail2 { get; set; }
        public virtual HR_ContractTime HR_ContractTime { get; set; }
        public virtual HR_ContractType HR_ContractType { get; set; }
        public virtual HR_Employee HR_Employee { get; set; }
        public virtual HR_PayrollCycleWage HR_PayrollCycleWage { get; set; }
        public virtual HR_PayrollFormPayment HR_PayrollFormPayment { get; set; }
        public virtual HR_PayRollWage HR_PayRollWage { get; set; }
        public virtual HR_SALARY_Shift HR_SALARY_Shift { get; set; }
        public virtual ICollection<HR_CycleWageHistory> HR_CycleWageHistory { get; set; }
        public virtual ICollection<HR_TimeKeepingSumary> HR_TimeKeepingSumary { get; set; }
    }
}
