//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Contract
    {
        public HR_Contract()
        {
            this.HR_ContractDetail = new HashSet<HR_ContractDetail>();
        }
    
        public int ContractId { get; set; }
        public int EmployeeId { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal SocialIncuranceSalary { get; set; }
        public decimal TotalAllowamces { get; set; }
        public decimal TotalAllowamcesHasTax { get; set; }
        public string ContractDetailIdsWait { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
        public virtual ICollection<HR_ContractDetail> HR_ContractDetail { get; set; }
    }
}
