//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_DailyWorkSchedule
    {
        public HR_DailyWorkSchedule()
        {
            this.HR_PeriodWorkScheduleOrder = new HashSet<HR_PeriodWorkScheduleOrder>();
            this.HR_Subtitution = new HashSet<HR_Subtitution>();
        }
    
        public int DailyWorkScheduleId { get; set; }
        public string DailyWorkScheduleName { get; set; }
        public string DailyWorkScheduleCode { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int TimeTypeGroupId { get; set; }
        public Nullable<int> BreakScheduleId { get; set; }
        public Nullable<double> PlannedWorkingHrs { get; set; }
        public Nullable<System.TimeSpan> BeginToleranceStart { get; set; }
        public System.TimeSpan BeginToleranceEnd { get; set; }
        public System.TimeSpan EndToleranceStart { get; set; }
        public System.TimeSpan EndToleranceEnd { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual HR_BreakSchedule HR_BreakSchedule { get; set; }
        public virtual ICollection<HR_PeriodWorkScheduleOrder> HR_PeriodWorkScheduleOrder { get; set; }
        public virtual ICollection<HR_Subtitution> HR_Subtitution { get; set; }
    }
}
