//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ErrorLog
    {
        public int ErrorId { get; set; }
        public byte ErrorType { get; set; }
        public string ErrorCaption { get; set; }
        public string ErrorContent { get; set; }
        public string ErrorClass { get; set; }
        public string ErrorMethod { get; set; }
        public string Source { get; set; }
        public string StackTrace { get; set; }
        public string IPError { get; set; }
        public string ActionError { get; set; }
        public string TargetSite { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
