//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Employee
    {
        public HR_Employee()
        {
            this.HR_AdvanceIncome = new HashSet<HR_AdvanceIncome>();
            this.HR_Contract = new HashSet<HR_Contract>();
            this.HR_ContractDetail = new HashSet<HR_ContractDetail>();
            this.HR_Employee1 = new HashSet<HR_Employee>();
            this.HR_EmployeeDepartment = new HashSet<HR_EmployeeDepartment>();
            this.HR_EmployeeJob = new HashSet<HR_EmployeeJob>();
            this.HR_EmployeePayrollFormula = new HashSet<HR_EmployeePayrollFormula>();
            this.HR_EmployeePayrollTable = new HashSet<HR_EmployeePayrollTable>();
            this.HR_EmployeeWSR = new HashSet<HR_EmployeeWSR>();
            this.HR_Families = new HashSet<HR_Families>();
            this.HR_InsuranceDetail = new HashSet<HR_InsuranceDetail>();
            this.HR_IrregularIncome = new HashSet<HR_IrregularIncome>();
            this.HR_OverTime = new HashSet<HR_OverTime>();
            this.HR_PayrollDetail = new HashSet<HR_PayrollDetail>();
            this.HR_PayrollStatus = new HashSet<HR_PayrollStatus>();
            this.HR_PayrollTableDetailData = new HashSet<HR_PayrollTableDetailData>();
            this.HR_PayrollTableInputData = new HashSet<HR_PayrollTableInputData>();
            this.HR_Promotion = new HashSet<HR_Promotion>();
            this.HR_SettlementTaxDetail = new HashSet<HR_SettlementTaxDetail>();
            this.HR_Subtitution = new HashSet<HR_Subtitution>();
            this.HR_TimeKeepingApproval = new HashSet<HR_TimeKeepingApproval>();
            this.HR_Vacation = new HashSet<HR_Vacation>();
            this.HR_VacationApprovalHistory = new HashSet<HR_VacationApprovalHistory>();
            this.HR_VacationApprovalUser = new HashSet<HR_VacationApprovalUser>();
            this.HR_VacationStore = new HashSet<HR_VacationStore>();
        }
    
        public int EmployeeID { get; set; }
        public Nullable<int> EmployeeIdOld { get; set; }
        public Nullable<int> UserId { get; set; }
        public string EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDay { get; set; }
        public bool Gender { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Image { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> CompanyBranchID { get; set; }
        public Nullable<int> CompanyOrganizationID { get; set; }
        public Nullable<int> CompanyPossitionID { get; set; }
        public Nullable<int> EmployeeMaritalID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> PeopleID { get; set; }
        public Nullable<int> OriginalID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<int> BirthProvinceID { get; set; }
        public string BirthAddress { get; set; }
        public Nullable<int> BirthDistricID { get; set; }
        public string EmailCompany { get; set; }
        public string Phone { get; set; }
        public string Ext { get; set; }
        public string PermanentAddress { get; set; }
        public Nullable<int> PermanentProvinceID { get; set; }
        public Nullable<int> PermanentDistricID { get; set; }
        public string TemporaryAddress { get; set; }
        public Nullable<int> TemporaryProvinceID { get; set; }
        public Nullable<int> TemporaryDistricID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Resign { get; set; }
        public string ReasonOffWork { get; set; }
        public Nullable<System.DateTime> EndTrialDate { get; set; }
        public Nullable<int> LevelProfessionID { get; set; }
        public Nullable<int> LevelForeignLangageID { get; set; }
        public Nullable<int> LevelInfomaticID { get; set; }
        public Nullable<int> LevelEducationID { get; set; }
        public Nullable<bool> HasTimeKeeping { get; set; }
        public Nullable<int> EmployeeGroupId { get; set; }
        public Nullable<int> EmployeeSubGroupId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> MachineEmployeeId { get; set; }
        public string Identification { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public string AddressOfIssue { get; set; }
        public Nullable<byte> EmployeeStatus { get; set; }
        public string TaxCode { get; set; }
        public Nullable<int> CompanyBusinessID { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<HR_AdvanceIncome> HR_AdvanceIncome { get; set; }
        public virtual ICollection<HR_Contract> HR_Contract { get; set; }
        public virtual ICollection<HR_ContractDetail> HR_ContractDetail { get; set; }
        public virtual ICollection<HR_Employee> HR_Employee1 { get; set; }
        public virtual HR_Employee HR_Employee2 { get; set; }
        public virtual HR_EmployeeGroup HR_EmployeeGroup { get; set; }
        public virtual HR_EmployeeSubGroup HR_EmployeeSubGroup { get; set; }
        public virtual HR_Organization HR_Organization { get; set; }
        public virtual HR_SALARY_Shift HR_SALARY_Shift { get; set; }
        public virtual ICollection<HR_EmployeeDepartment> HR_EmployeeDepartment { get; set; }
        public virtual ICollection<HR_EmployeeJob> HR_EmployeeJob { get; set; }
        public virtual HR_EmployeeMobivi HR_EmployeeMobivi { get; set; }
        public virtual ICollection<HR_EmployeePayrollFormula> HR_EmployeePayrollFormula { get; set; }
        public virtual ICollection<HR_EmployeePayrollTable> HR_EmployeePayrollTable { get; set; }
        public virtual ICollection<HR_EmployeeWSR> HR_EmployeeWSR { get; set; }
        public virtual ICollection<HR_Families> HR_Families { get; set; }
        public virtual ICollection<HR_InsuranceDetail> HR_InsuranceDetail { get; set; }
        public virtual ICollection<HR_IrregularIncome> HR_IrregularIncome { get; set; }
        public virtual ICollection<HR_OverTime> HR_OverTime { get; set; }
        public virtual ICollection<HR_PayrollDetail> HR_PayrollDetail { get; set; }
        public virtual ICollection<HR_PayrollStatus> HR_PayrollStatus { get; set; }
        public virtual ICollection<HR_PayrollTableDetailData> HR_PayrollTableDetailData { get; set; }
        public virtual ICollection<HR_PayrollTableInputData> HR_PayrollTableInputData { get; set; }
        public virtual ICollection<HR_Promotion> HR_Promotion { get; set; }
        public virtual ICollection<HR_SettlementTaxDetail> HR_SettlementTaxDetail { get; set; }
        public virtual ICollection<HR_Subtitution> HR_Subtitution { get; set; }
        public virtual ICollection<HR_TimeKeepingApproval> HR_TimeKeepingApproval { get; set; }
        public virtual ICollection<HR_Vacation> HR_Vacation { get; set; }
        public virtual ICollection<HR_VacationApprovalHistory> HR_VacationApprovalHistory { get; set; }
        public virtual ICollection<HR_VacationApprovalUser> HR_VacationApprovalUser { get; set; }
        public virtual ICollection<HR_VacationStore> HR_VacationStore { get; set; }
    }
}
