//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EmployeeWSR
    {
        public int EmployeeWSR { get; set; }
        public int EmployeeId { get; set; }
        public int WorkScheduleId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int CompanyId { get; set; }
        public Nullable<bool> HasTimekeeping { get; set; }
        public Nullable<int> ObjectWSRDetailId { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
        public virtual HR_ObjectWSRDetail HR_ObjectWSRDetail { get; set; }
        public virtual HR_WorkScheduleRule HR_WorkScheduleRule { get; set; }
    }
}
