//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Families
    {
        public int FamiliesID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Picture { get; set; }
        public string Address { get; set; }
        public Nullable<int> CounTryId { get; set; }
        public Nullable<int> ProvincesId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Job { get; set; }
        public string WorkAddress { get; set; }
        public Nullable<int> FamilyRelationShipID { get; set; }
        public string IDNumber { get; set; }
        public string TaxCode { get; set; }
        public Nullable<System.DateTime> StartDateEnable { get; set; }
        public Nullable<System.DateTime> EndDateEnable { get; set; }
        public bool isDepedent { get; set; }
        public bool isApproval { get; set; }
        public Nullable<bool> isDie { get; set; }
        public Nullable<System.DateTime> DeathDay { get; set; }
        public string Note { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
        public virtual HR_FamilyRelationship HR_FamilyRelationship { get; set; }
    }
}
