//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_InsuranceType
    {
        public HR_InsuranceType()
        {
            this.HR_InsuranceConfig = new HashSet<HR_InsuranceConfig>();
        }
    
        public int InsuranceType { get; set; }
        public string InsuranceName { get; set; }
    
        public virtual ICollection<HR_InsuranceConfig> HR_InsuranceConfig { get; set; }
    }
}
