//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_MobiviAPI
    {
        public int CertificateId { get; set; }
        public string SubjectCompany { get; set; }
        public int CompanyId { get; set; }
        public Nullable<System.DateTime> CutOffDate { get; set; }
    }
}
