//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ObjectWSRDetail
    {
        public HR_ObjectWSRDetail()
        {
            this.HR_EmployeeWSR = new HashSet<HR_EmployeeWSR>();
        }
    
        public int Id { get; set; }
        public int ObjectWSRId { get; set; }
        public int ObjectId { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<HR_EmployeeWSR> HR_EmployeeWSR { get; set; }
        public virtual HR_ObjectWSR HR_ObjectWSR { get; set; }
    }
}
