//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Organization
    {
        public HR_Organization()
        {
            this.HR_Employee = new HashSet<HR_Employee>();
            this.HR_PartOfOrganization = new HashSet<HR_PartOfOrganization>();
            this.HR_Position = new HashSet<HR_Position>();
            this.HR_Promotion = new HashSet<HR_Promotion>();
        }
    
        public int OrganizationId { get; set; }
        public int ParentId { get; set; }
        public string Node { get; set; }
        public int OrderIndex { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Note { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<HR_Employee> HR_Employee { get; set; }
        public virtual ICollection<HR_PartOfOrganization> HR_PartOfOrganization { get; set; }
        public virtual ICollection<HR_Position> HR_Position { get; set; }
        public virtual ICollection<HR_Promotion> HR_Promotion { get; set; }
    }
}
