//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Payroll
    {
        public HR_Payroll()
        {
            this.HR_PayrollDetail = new HashSet<HR_PayrollDetail>();
            this.HR_PayrollStatus = new HashSet<HR_PayrollStatus>();
        }
    
        public int PayrollId { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool Looked { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsApprove { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<int> HR_PayrollFormula_PayrollFormulaId { get; set; }
    
        public virtual HR_PayrollFormula HR_PayrollFormula { get; set; }
        public virtual ICollection<HR_PayrollDetail> HR_PayrollDetail { get; set; }
        public virtual ICollection<HR_PayrollStatus> HR_PayrollStatus { get; set; }
    }
}
