//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PayRollWage
    {
        public HR_PayRollWage()
        {
            this.HR_ContractDetail = new HashSet<HR_ContractDetail>();
        }
    
        public int PayrollWageID { get; set; }
        public int PayrollSalaryRankID { get; set; }
        public int Rank { get; set; }
        public double Coefficient { get; set; }
        public decimal Wage { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<HR_ContractDetail> HR_ContractDetail { get; set; }
        public virtual HR_PayrollSalaryRank HR_PayrollSalaryRank { get; set; }
    }
}
