//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PeriodWorkSchedule
    {
        public HR_PeriodWorkSchedule()
        {
            this.HR_PeriodWorkScheduleOrder = new HashSet<HR_PeriodWorkScheduleOrder>();
            this.HR_PWS_WSR = new HashSet<HR_PWS_WSR>();
        }
    
        public int PeriodWorkScheduleId { get; set; }
        public string PeriodWorkScheduleName { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<HR_PeriodWorkScheduleOrder> HR_PeriodWorkScheduleOrder { get; set; }
        public virtual ICollection<HR_PWS_WSR> HR_PWS_WSR { get; set; }
    }
}
