//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PayrollFormula
    {
        public HR_PayrollFormula()
        {
            this.HR_EmployeePayrollFormula = new HashSet<HR_EmployeePayrollFormula>();
            this.HR_Payroll = new HashSet<HR_Payroll>();
        }
    
        public int PayrollFormulaId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string FormulaString { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> EmployeeGroupId { get; set; }
        public string FormulaName { get; set; }
        public string FormulaDescription { get; set; }
    
        public virtual ICollection<HR_EmployeePayrollFormula> HR_EmployeePayrollFormula { get; set; }
        public virtual ICollection<HR_Payroll> HR_Payroll { get; set; }
    }
}
