//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PayrollShareList
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int PayrollId { get; set; }
        public Nullable<int> Method { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
