//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PayrollDataTime
    {
        public int PayrollDataId { get; set; }
        public int TimeTypeId { get; set; }
        public double Time { get; set; }
    
        public virtual HR_PayrollData HR_PayrollData { get; set; }
        public virtual HR_TimeType HR_TimeType { get; set; }
    }
}
