//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PayrollSalaryRank
    {
        public HR_PayrollSalaryRank()
        {
            this.HR_PayRollWage = new HashSet<HR_PayRollWage>();
        }
    
        public int PayrollSalaryRankID { get; set; }
        public int PayrollWageScaleID { get; set; }
        public string Notation { get; set; }
        public string Name { get; set; }
        public Nullable<int> MaxRank { get; set; }
        public Nullable<double> CoefficientStart { get; set; }
        public Nullable<double> CoefficientGrowth { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual HR_PayrollWageScale HR_PayrollWageScale { get; set; }
        public virtual ICollection<HR_PayRollWage> HR_PayRollWage { get; set; }
    }
}
