//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PayrollTable
    {
        public HR_PayrollTable()
        {
            this.HR_EmployeePayrollTable = new HashSet<HR_EmployeePayrollTable>();
            this.HR_PayrollTableDetail = new HashSet<HR_PayrollTableDetail>();
            this.HR_PayrollTableInput = new HashSet<HR_PayrollTableInput>();
        }
    
        public int PayrollTableID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public int CompanyID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<HR_EmployeePayrollTable> HR_EmployeePayrollTable { get; set; }
        public virtual ICollection<HR_PayrollTableDetail> HR_PayrollTableDetail { get; set; }
        public virtual ICollection<HR_PayrollTableInput> HR_PayrollTableInput { get; set; }
    }
}
