//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PayrollCycleWageDetail
    {
        public HR_PayrollCycleWageDetail()
        {
            this.HR_PayrollDetail = new HashSet<HR_PayrollDetail>();
            this.HR_PayrollStatus = new HashSet<HR_PayrollStatus>();
            this.HR_TimeKeepingSumary = new HashSet<HR_TimeKeepingSumary>();
        }
    
        public int CycleWageDetailId { get; set; }
        public int CycleWageID { get; set; }
        public int FromDay { get; set; }
        public int ToDay { get; set; }
        public string Name { get; set; }
        public int CompanyId { get; set; }
    
        public virtual HR_PayrollCycleWage HR_PayrollCycleWage { get; set; }
        public virtual ICollection<HR_PayrollDetail> HR_PayrollDetail { get; set; }
        public virtual ICollection<HR_PayrollStatus> HR_PayrollStatus { get; set; }
        public virtual ICollection<HR_TimeKeepingSumary> HR_TimeKeepingSumary { get; set; }
    }
}
