//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PayrollStatus
    {
        public int PayrollId { get; set; }
        public int EmployeeID { get; set; }
        public int CycleWageDetailId { get; set; }
        public int PayrollStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
        public virtual HR_Payroll HR_Payroll { get; set; }
        public virtual HR_PayrollCycleWageDetail HR_PayrollCycleWageDetail { get; set; }
    }
}
