//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PayrollData
    {
        public HR_PayrollData()
        {
            this.HR_PayrollDetail = new HashSet<HR_PayrollDetail>();
            this.HR_PayrollDataTime = new HashSet<HR_PayrollDataTime>();
        }
    
        public int PayrollDataId { get; set; }
        public int EmployeeId { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal SISalary { get; set; }
        public decimal TotalAllowance { get; set; }
        public decimal TotalAllowanceHasTax { get; set; }
        public decimal IISalary { get; set; }
        public decimal IISalaryHasTax { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<HR_PayrollDetail> HR_PayrollDetail { get; set; }
        public virtual ICollection<HR_PayrollDataTime> HR_PayrollDataTime { get; set; }
    }
}
