//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_SettlementTaxDetail
    {
        public int SettlementTaxId { get; set; }
        public int EmployeeId { get; set; }
        public decimal TotalGrossSalary { get; set; }
        public decimal TotalSettlementTax { get; set; }
        public decimal TotalDeductionTax { get; set; }
        public bool IsFull { get; set; }
        public bool IsHalf { get; set; }
        public decimal TotalDeductionFamily { get; set; }
        public decimal TotalDeInsurance { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
        public virtual HR_SettlementTax HR_SettlementTax { get; set; }
    }
}
