//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_TimeKeepingSumary
    {
        public int ID { get; set; }
        public int EmployeeId { get; set; }
        public int ContractDetailId { get; set; }
        public int CycleWageDetailId { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal SocialIncuranceSalary { get; set; }
        public decimal TotalAllowamces { get; set; }
        public decimal TotalIncome { get; set; }
        public double DailyWorkingTime { get; set; }
        public double DayWorkingTime { get; set; }
        public double OverTime { get; set; }
        public double VacationTime { get; set; }
        public double TimeLate { get; set; }
        public double TimeSoon { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int TotalDepedent { get; set; }
        public double WorkingOverTimeSalary { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public decimal MobiviAllowances { get; set; }
        public decimal IncomeTax { get; set; }
    
        public virtual HR_ContractDetail HR_ContractDetail { get; set; }
        public virtual HR_PayrollCycleWageDetail HR_PayrollCycleWageDetail { get; set; }
    }
}
