//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_TimeKeepingApproval
    {
        public int TimeKeepingApproval { get; set; }
        public int EmployeeId { get; set; }
        public int TimeTypeId { get; set; }
        public double Time { get; set; }
        public System.DateTime DateOn { get; set; }
        public double TimeLate { get; set; }
        public double TimeSoon { get; set; }
        public int TimeKeepingID { get; set; }
        public bool IsOverTime { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
        public virtual HR_TimeKeeping HR_TimeKeeping { get; set; }
        public virtual HR_TimeType HR_TimeType { get; set; }
    }
}
