//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_TimeType
    {
        public HR_TimeType()
        {
            this.HR_PayrollDataTime = new HashSet<HR_PayrollDataTime>();
            this.HR_TimeKeepingApproval = new HashSet<HR_TimeKeepingApproval>();
            this.HR_TimeTypeGroup = new HashSet<HR_TimeTypeGroup>();
        }
    
        public int TimeTypeId { get; set; }
        public string TimeTypeCode { get; set; }
        public string Name { get; set; }
        public double Multipliper { get; set; }
        public int DayType { get; set; }
        public int Type { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<HR_PayrollDataTime> HR_PayrollDataTime { get; set; }
        public virtual ICollection<HR_TimeKeepingApproval> HR_TimeKeepingApproval { get; set; }
        public virtual ICollection<HR_TimeTypeGroup> HR_TimeTypeGroup { get; set; }
    }
}
