//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_TimeKeepingDetail
    {
        public long TimeKeepingDetailId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime TimeKeeping { get; set; }
        public short TimeEvent { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public Nullable<int> TerminalId { get; set; }
        public string Note { get; set; }
        public Nullable<int> TimeKeepingID { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual HR_TimeKeeping HR_TimeKeeping { get; set; }
    }
}
