//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_TimeKeeping
    {
        public HR_TimeKeeping()
        {
            this.HR_TimeKeepingApproval = new HashSet<HR_TimeKeepingApproval>();
            this.HR_TimeKeepingDetail = new HashSet<HR_TimeKeepingDetail>();
        }
    
        public int TimeKeepingID { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime TimeKeeping { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.TimeSpan ConfirmStartTime { get; set; }
        public System.TimeSpan ComfirmEndTime { get; set; }
        public int ConfirmUserId { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string ConfirmIP { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CompanyID { get; set; }
        public Nullable<bool> ComfirmStatus { get; set; }
        public string Note { get; set; }
        public Nullable<int> TerminalId { get; set; }
        public bool HasApproval { get; set; }
        public bool IsException { get; set; }
        public Nullable<int> DailyWorkSheduleId { get; set; }
    
        public virtual ICollection<HR_TimeKeepingApproval> HR_TimeKeepingApproval { get; set; }
        public virtual ICollection<HR_TimeKeepingDetail> HR_TimeKeepingDetail { get; set; }
    }
}
