//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_VacationType
    {
        public HR_VacationType()
        {
            this.HR_Vacation = new HashSet<HR_Vacation>();
            this.HR_VacationStore = new HashSet<HR_VacationStore>();
        }
    
        public int VacationTypeId { get; set; }
        public int VacationTypeGroupId { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public string Notation { get; set; }
        public int MaxDays { get; set; }
        public bool HasPayRoll { get; set; }
        public bool IncludeOffDay { get; set; }
        public bool EndDayRequired { get; set; }
        public bool SubtractAll { get; set; }
        public string Note { get; set; }
        public bool IsActived { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool DependingOnMonth { get; set; }
        public Nullable<int> InsuranceVacationType { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual ICollection<HR_Vacation> HR_Vacation { get; set; }
        public virtual ICollection<HR_VacationStore> HR_VacationStore { get; set; }
        public virtual HR_VacationTypeGroup HR_VacationTypeGroup { get; set; }
    }
}
