//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_VacationApproval
    {
        public HR_VacationApproval()
        {
            this.HR_VacationApprovalUser = new HashSet<HR_VacationApprovalUser>();
        }
    
        public int VacationApprovalId { get; set; }
        public string ApprovalName { get; set; }
        public int OrderApproval { get; set; }
        public double MaxDay { get; set; }
        public bool IsMaster { get; set; }
        public string Description { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool ApprovalTypeConfig { get; set; }
    
        public virtual ICollection<HR_VacationApprovalUser> HR_VacationApprovalUser { get; set; }
    }
}
