//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_VacationStore
    {
        public int VacationStoreId { get; set; }
        public int EmployeeId { get; set; }
        public int CompanyId { get; set; }
        public int VacationTypeId { get; set; }
        public System.DateTime ValidTo { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime DeductionFrom { get; set; }
        public System.DateTime DeductionTo { get; set; }
        public double Amount { get; set; }
        public double Accumulated { get; set; }
        public double TempAccumulated { get; set; }
        public string AdministratorNote { get; set; }
        public Nullable<int> CurrentMonth { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
        public virtual HR_VacationType HR_VacationType { get; set; }
    }
}
