//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Vacation
    {
        public HR_Vacation()
        {
            this.HR_VacationApprovalHistory = new HashSet<HR_VacationApprovalHistory>();
            this.HR_VacationDetail = new HashSet<HR_VacationDetail>();
        }
    
        public int VacationId { get; set; }
        public int VacationTypeId { get; set; }
        public int EmployeeId { get; set; }
        public string ListEmployeeId { get; set; }
        public int CompanyId { get; set; }
        public string Reasons { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> Days { get; set; }
        public Nullable<bool> Allow { get; set; }
        public bool IsCheckDepartment { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
        public virtual HR_VacationType HR_VacationType { get; set; }
        public virtual ICollection<HR_VacationApprovalHistory> HR_VacationApprovalHistory { get; set; }
        public virtual ICollection<HR_VacationDetail> HR_VacationDetail { get; set; }
    }
}
