//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_VacationOverTimeApply
    {
        public int VacationOverTimeApplyId { get; set; }
        public int Type { get; set; }
        public Nullable<int> EEGroup { get; set; }
        public Nullable<int> EESubGroup { get; set; }
        public int TimeTypeGroupId { get; set; }
        public int CompanyID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual HR_EmployeeGroup HR_EmployeeGroup { get; set; }
        public virtual HR_EmployeeSubGroup HR_EmployeeSubGroup { get; set; }
        public virtual HR_TimeTypeGroup HR_TimeTypeGroup { get; set; }
    }
}
