//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_WorkScheduleRule
    {
        public HR_WorkScheduleRule()
        {
            this.HR_EmployeeWSR = new HashSet<HR_EmployeeWSR>();
            this.HR_MasterWorkScheduleRule = new HashSet<HR_MasterWorkScheduleRule>();
            this.HR_ObjectWSR = new HashSet<HR_ObjectWSR>();
            this.HR_PWS_WSR = new HashSet<HR_PWS_WSR>();
        }
    
        public int WorkScheduleId { get; set; }
        public string WorkScheduleCode { get; set; }
        public string WorkScheduleName { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<HR_EmployeeWSR> HR_EmployeeWSR { get; set; }
        public virtual ICollection<HR_MasterWorkScheduleRule> HR_MasterWorkScheduleRule { get; set; }
        public virtual ICollection<HR_ObjectWSR> HR_ObjectWSR { get; set; }
        public virtual ICollection<HR_PWS_WSR> HR_PWS_WSR { get; set; }
    }
}
