//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMEntities : DbContext
    {
        public HRMEntities()
            : base("name=HRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HR_AdvanceIncome> HR_AdvanceIncome { get; set; }
        public DbSet<HR_BreakSchedule> HR_BreakSchedule { get; set; }
        public DbSet<HR_Config> HR_Config { get; set; }
        public DbSet<HR_Contract> HR_Contract { get; set; }
        public DbSet<HR_ContractAllowances> HR_ContractAllowances { get; set; }
        public DbSet<HR_ContractDetail> HR_ContractDetail { get; set; }
        public DbSet<HR_ContractTemplate> HR_ContractTemplate { get; set; }
        public DbSet<HR_ContractTime> HR_ContractTime { get; set; }
        public DbSet<HR_ContractType> HR_ContractType { get; set; }
        public DbSet<HR_CreditRange> HR_CreditRange { get; set; }
        public DbSet<HR_CycleWageHistory> HR_CycleWageHistory { get; set; }
        public DbSet<HR_DailyWorkSchedule> HR_DailyWorkSchedule { get; set; }
        public DbSet<HR_Employee> HR_Employee { get; set; }
        public DbSet<HR_EmployeeDepartment> HR_EmployeeDepartment { get; set; }
        public DbSet<HR_EmployeeGroup> HR_EmployeeGroup { get; set; }
        public DbSet<HR_EmployeeJob> HR_EmployeeJob { get; set; }
        public DbSet<HR_EmployeeMarital> HR_EmployeeMarital { get; set; }
        public DbSet<HR_EmployeeMobivi> HR_EmployeeMobivi { get; set; }
        public DbSet<HR_EmployeePayrollFormula> HR_EmployeePayrollFormula { get; set; }
        public DbSet<HR_EmployeePayrollTable> HR_EmployeePayrollTable { get; set; }
        public DbSet<HR_EmployeeSubGroup> HR_EmployeeSubGroup { get; set; }
        public DbSet<HR_EmployeeTechnique> HR_EmployeeTechnique { get; set; }
        public DbSet<HR_EmployeeWSR> HR_EmployeeWSR { get; set; }
        public DbSet<HR_ErrorLog> HR_ErrorLog { get; set; }
        public DbSet<HR_Families> HR_Families { get; set; }
        public DbSet<HR_FamilyRelationship> HR_FamilyRelationship { get; set; }
        public DbSet<HR_FileObject> HR_FileObject { get; set; }
        public DbSet<HR_Hospital> HR_Hospital { get; set; }
        public DbSet<HR_InsuranceConfig> HR_InsuranceConfig { get; set; }
        public DbSet<HR_InsuranceDetail> HR_InsuranceDetail { get; set; }
        public DbSet<HR_InsuranceType> HR_InsuranceType { get; set; }
        public DbSet<HR_IrregularIncome> HR_IrregularIncome { get; set; }
        public DbSet<HR_JobTitle> HR_JobTitle { get; set; }
        public DbSet<HR_MasterWorkScheduleRule> HR_MasterWorkScheduleRule { get; set; }
        public DbSet<HR_MobiviAPI> HR_MobiviAPI { get; set; }
        public DbSet<HR_MoneyType> HR_MoneyType { get; set; }
        public DbSet<HR_ObjectWSR> HR_ObjectWSR { get; set; }
        public DbSet<HR_ObjectWSRDetail> HR_ObjectWSRDetail { get; set; }
        public DbSet<HR_Organization> HR_Organization { get; set; }
        public DbSet<HR_OverTime> HR_OverTime { get; set; }
        public DbSet<HR_OverTimeObject> HR_OverTimeObject { get; set; }
        public DbSet<HR_OverTimeObject_Detail> HR_OverTimeObject_Detail { get; set; }
        public DbSet<HR_PartOfOrganization> HR_PartOfOrganization { get; set; }
        public DbSet<HR_Payroll> HR_Payroll { get; set; }
        public DbSet<HR_PayrollAllowances> HR_PayrollAllowances { get; set; }
        public DbSet<HR_PayrollCycleWage> HR_PayrollCycleWage { get; set; }
        public DbSet<HR_PayrollCycleWageAllocation> HR_PayrollCycleWageAllocation { get; set; }
        public DbSet<HR_PayrollCycleWageDetail> HR_PayrollCycleWageDetail { get; set; }
        public DbSet<HR_PayrollData> HR_PayrollData { get; set; }
        public DbSet<HR_PayrollDataTime> HR_PayrollDataTime { get; set; }
        public DbSet<HR_PayrollDetail> HR_PayrollDetail { get; set; }
        public DbSet<HR_PayrollFormPayment> HR_PayrollFormPayment { get; set; }
        public DbSet<HR_PayrollFormula> HR_PayrollFormula { get; set; }
        public DbSet<HR_PayrollFormulaShare> HR_PayrollFormulaShare { get; set; }
        public DbSet<HR_PayrollSalaryRank> HR_PayrollSalaryRank { get; set; }
        public DbSet<HR_PayrollShareList> HR_PayrollShareList { get; set; }
        public DbSet<HR_PayrollStatus> HR_PayrollStatus { get; set; }
        public DbSet<HR_PayrollSumary> HR_PayrollSumary { get; set; }
        public DbSet<HR_PayrollTable> HR_PayrollTable { get; set; }
        public DbSet<HR_PayrollTableDetail> HR_PayrollTableDetail { get; set; }
        public DbSet<HR_PayrollTableDetailData> HR_PayrollTableDetailData { get; set; }
        public DbSet<HR_PayrollTableInput> HR_PayrollTableInput { get; set; }
        public DbSet<HR_PayrollTableInputData> HR_PayrollTableInputData { get; set; }
        public DbSet<HR_PayrollTableShare> HR_PayrollTableShare { get; set; }
        public DbSet<HR_PayRollWage> HR_PayRollWage { get; set; }
        public DbSet<HR_PayrollWageScale> HR_PayrollWageScale { get; set; }
        public DbSet<HR_PeriodWorkSchedule> HR_PeriodWorkSchedule { get; set; }
        public DbSet<HR_PeriodWorkScheduleOrder> HR_PeriodWorkScheduleOrder { get; set; }
        public DbSet<HR_Position> HR_Position { get; set; }
        public DbSet<HR_Promotion> HR_Promotion { get; set; }
        public DbSet<HR_PWS_WSR> HR_PWS_WSR { get; set; }
        public DbSet<HR_SALARY_Shift> HR_SALARY_Shift { get; set; }
        public DbSet<HR_SettlementTax> HR_SettlementTax { get; set; }
        public DbSet<HR_SettlementTaxDetail> HR_SettlementTaxDetail { get; set; }
        public DbSet<HR_Subtitution> HR_Subtitution { get; set; }
        public DbSet<HR_SubtitutionObject> HR_SubtitutionObject { get; set; }
        public DbSet<HR_SubtitutionObject_Detail> HR_SubtitutionObject_Detail { get; set; }
        public DbSet<HR_Tariff> HR_Tariff { get; set; }
        public DbSet<HR_TimeKeeping> HR_TimeKeeping { get; set; }
        public DbSet<HR_TimeKeepingApproval> HR_TimeKeepingApproval { get; set; }
        public DbSet<HR_TimeKeepingApprovalError> HR_TimeKeepingApprovalError { get; set; }
        public DbSet<HR_TimeKeepingDetail> HR_TimeKeepingDetail { get; set; }
        public DbSet<HR_TimeKeepingSumary> HR_TimeKeepingSumary { get; set; }
        public DbSet<HR_TimeType> HR_TimeType { get; set; }
        public DbSet<HR_TimeTypeGroup> HR_TimeTypeGroup { get; set; }
        public DbSet<HR_Vacation> HR_Vacation { get; set; }
        public DbSet<HR_VacationApproval> HR_VacationApproval { get; set; }
        public DbSet<HR_VacationApprovalHistory> HR_VacationApprovalHistory { get; set; }
        public DbSet<HR_VacationApprovalUser> HR_VacationApprovalUser { get; set; }
        public DbSet<HR_VacationDetail> HR_VacationDetail { get; set; }
        public DbSet<HR_VacationException> HR_VacationException { get; set; }
        public DbSet<HR_VacationExceptionApply> HR_VacationExceptionApply { get; set; }
        public DbSet<HR_VacationInsurance> HR_VacationInsurance { get; set; }
        public DbSet<HR_VacationInsuranceType> HR_VacationInsuranceType { get; set; }
        public DbSet<HR_VacationMuch> HR_VacationMuch { get; set; }
        public DbSet<HR_VacationOverTimeApply> HR_VacationOverTimeApply { get; set; }
        public DbSet<HR_VacationStore> HR_VacationStore { get; set; }
        public DbSet<HR_VacationTime> HR_VacationTime { get; set; }
        public DbSet<HR_VacationType> HR_VacationType { get; set; }
        public DbSet<HR_VacationTypeGroup> HR_VacationTypeGroup { get; set; }
        public DbSet<HR_WorkScheduleRule> HR_WorkScheduleRule { get; set; }
        public DbSet<TA_TimeLog> TA_TimeLog { get; set; }
    }
}
