//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_CompletionPhase
    {
        public P_CompletionPhase()
        {
            this.P_CompletionPhase_Daily = new HashSet<P_CompletionPhase_Daily>();
            this.P_PhaseDaily = new HashSet<P_PhaseDaily>();
        }
    
        public int Id { get; set; }
        public int OrderIndex { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsShow { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<P_CompletionPhase_Daily> P_CompletionPhase_Daily { get; set; }
        public virtual ICollection<P_PhaseDaily> P_PhaseDaily { get; set; }
    }
}
