//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_PM_JobGroup
    {
        public P_PM_JobGroup()
        {
            this.P_PM_Job = new HashSet<P_PM_Job>();
        }
    
        public int Id { get; set; }
        public int ParentId { get; set; }
        public int JobGroupId { get; set; }
        public int PartOfOrganId { get; set; }
        public string Node { get; set; }
        public int OrderIndex { get; set; }
        public string Note { get; set; }
        public bool IsHasRHomebus { get; set; }
        public string RHomebusTitle { get; set; }
        public int StatusId { get; set; }
        public int PercentComplete { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual P_JobGroup P_JobGroup { get; set; }
        public virtual ICollection<P_PM_Job> P_PM_Job { get; set; }
        public virtual P_ProManagement P_ProManagement { get; set; }
    }
}
