//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_PM_Job
    {
        public P_PM_Job()
        {
            this.P_PM_EmployeeReference = new HashSet<P_PM_EmployeeReference>();
            this.P_PM_JobDetail = new HashSet<P_PM_JobDetail>();
        }
    
        public int Id { get; set; }
        public int PM_JobGroupId { get; set; }
        public int JobId { get; set; }
        public int OrderIndex { get; set; }
        public System.DateTime TimeStart { get; set; }
        public System.DateTime TimeEnd { get; set; }
        public Nullable<System.DateTime> RealTimeEnd { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public int EmployeeId { get; set; }
        public int StatusId { get; set; }
        public int PercentComplete { get; set; }
        public string ErrorMessage { get; set; }
        public string UserMessage { get; set; }
        public bool RequiredApprove { get; set; }
        public bool IsApprove { get; set; }
        public string ApproveMessage { get; set; }
        public bool IsStopAlarm { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual P_Job P_Job { get; set; }
        public virtual ICollection<P_PM_EmployeeReference> P_PM_EmployeeReference { get; set; }
        public virtual P_PM_JobGroup P_PM_JobGroup { get; set; }
        public virtual ICollection<P_PM_JobDetail> P_PM_JobDetail { get; set; }
    }
}
