//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SArea
    {
        public SArea()
        {
            this.SProvinces = new HashSet<SProvince>();
            this.SDistricts = new HashSet<SDistrict>();
        }
    
        public int Id { get; set; }
        public int CountryID { get; set; }
        public string AreaName { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual SCountry SCountry { get; set; }
        public virtual ICollection<SProvince> SProvinces { get; set; }
        public virtual ICollection<SDistrict> SDistricts { get; set; }
    }
}
