//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCheckList_Config
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int JobId { get; set; }
        public bool HasMenu { get; set; }
        public Nullable<int> ModuleId_Menu { get; set; }
        public string TableName_Menu { get; set; }
        public string EventAdd_Menu { get; set; }
        public string EventDelete_Menu { get; set; }
        public Nullable<int> ModuleId_WH { get; set; }
        public string TableName_WH { get; set; }
        public string EventAdd_WH { get; set; }
        public string EventDelete_WH { get; set; }
        public Nullable<int> ModuleId_Pro { get; set; }
        public string TableName_Pro { get; set; }
        public string EventAdd_Pro { get; set; }
        public string EventDelete_Pro { get; set; }
        public bool IsDefault { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual SModule SModule { get; set; }
    }
}
