//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCompany
    {
        public SCompany()
        {
            this.SCompany1 = new HashSet<SCompany>();
            this.SUsers = new HashSet<SUser>();
            this.SRoLes = new HashSet<SRoLe>();
            this.SCompanyModules = new HashSet<SCompanyModule>();
        }
    
        public int Id { get; set; }
        public int LevelCompanyId { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string TaxCode { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ParentNode { get; set; }
        public string Logo { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsOwner { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<SCompany> SCompany1 { get; set; }
        public virtual SCompany SCompany2 { get; set; }
        public virtual ICollection<SUser> SUsers { get; set; }
        public virtual ICollection<SRoLe> SRoLes { get; set; }
        public virtual ICollection<SCompanyModule> SCompanyModules { get; set; }
    }
}
