//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCountry
    {
        public SCountry()
        {
            this.SAreas = new HashSet<SArea>();
            this.SBankBranches = new HashSet<SBankBranch>();
            this.SProvinces = new HashSet<SProvince>();
            this.SDistricts = new HashSet<SDistrict>();
            this.SHospitals = new HashSet<SHospital>();
            this.SRaces = new HashSet<SRace>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string CountryName { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<SArea> SAreas { get; set; }
        public virtual ICollection<SBankBranch> SBankBranches { get; set; }
        public virtual ICollection<SProvince> SProvinces { get; set; }
        public virtual ICollection<SDistrict> SDistricts { get; set; }
        public virtual ICollection<SHospital> SHospitals { get; set; }
        public virtual ICollection<SRace> SRaces { get; set; }
    }
}
