//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDistrict
    {
        public SDistrict()
        {
            this.SBankBranches = new HashSet<SBankBranch>();
            this.SHospitals = new HashSet<SHospital>();
        }
    
        public int Id { get; set; }
        public int CountryId { get; set; }
        public int AreaId { get; set; }
        public int ProvinceId { get; set; }
        public string DistrictName { get; set; }
        public string Code { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual SArea SArea { get; set; }
        public virtual ICollection<SBankBranch> SBankBranches { get; set; }
        public virtual SCountry SCountry { get; set; }
        public virtual SProvince SProvince { get; set; }
        public virtual ICollection<SHospital> SHospitals { get; set; }
    }
}
