//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFeature
    {
        public SFeature()
        {
            this.SPermissions = new HashSet<SPermission>();
            this.SRolePermissions = new HashSet<SRolePermission>();
        }
    
        public int Id { get; set; }
        public string FeatureName { get; set; }
        public string SystemName { get; set; }
        public int ModuleId { get; set; }
        public string Description { get; set; }
        public bool IsSystem { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsDefault { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual SModule SModule { get; set; }
        public virtual ICollection<SPermission> SPermissions { get; set; }
        public virtual ICollection<SRolePermission> SRolePermissions { get; set; }
    }
}
