//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPermission
    {
        public SPermission()
        {
            this.SRolePermissions = new HashSet<SRolePermission>();
        }
    
        public int Id { get; set; }
        public int FeatureId { get; set; }
        public int PermissionTypeId { get; set; }
        public string SystemName { get; set; }
        public string PermissionName { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsDefault { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual SFeature SFeature { get; set; }
        public virtual ICollection<SRolePermission> SRolePermissions { get; set; }
    }
}
