//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SProvince
    {
        public SProvince()
        {
            this.SBankBranches = new HashSet<SBankBranch>();
            this.SDistricts = new HashSet<SDistrict>();
            this.SHospitals = new HashSet<SHospital>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AreaId { get; set; }
        public int CountryId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string PhoneCode { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual SArea SArea { get; set; }
        public virtual ICollection<SBankBranch> SBankBranches { get; set; }
        public virtual SCountry SCountry { get; set; }
        public virtual ICollection<SDistrict> SDistricts { get; set; }
        public virtual ICollection<SHospital> SHospitals { get; set; }
    }
}
